CREATE TABLE cliente (
	identificacion varchar NOT NULL,
	nombre varchar NOT NULL,
	apellido varchar NOT NULL,
	CONSTRAINT cliente_pk PRIMARY KEY (identificacion)
);

CREATE TABLE factura (
	id_factura int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	fecha date NOT NULL,
	descripcion varchar NULL,
	id_cliente varchar NOT NULL,
	CONSTRAINT factura_pk PRIMARY KEY (id_factura),
	CONSTRAINT factura_fk FOREIGN KEY (id_cliente) REFERENCES cliente(identificacion)
);

CREATE TABLE producto (
	id_producto int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar NOT NULL,
	precio_unitario float4 NOT NULL,
	CONSTRAINT producto_pk PRIMARY KEY (id_producto)
);

CREATE TABLE lote (
	id_lote int4 NOT NULL,
	laboratorio varchar NOT NULL,
	fecha_vencimiento date NOT NULL,
	cantidad int4 NOT NULL,
	id_producto int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT lote_pk PRIMARY KEY (id_lote),
	CONSTRAINT lote_fk FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);
